apiVersion: v1
kind: Service
metadata:
  name: certbot
  labels:
    app: certbot
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: empty
      port: 3099
      targetPort: 3099
  selector:
    app: certbot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
      - delete
      - create
      - update
      - patch
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certbot
subjects:
- kind: ServiceAccount
  name: certbot
  namespace: default